[package]
name = "eth-rpc-tests"
version = "0.1.0"
edition = "2021"

[dependencies]

[dev-dependencies]
reqwest      = { workspace = true, features = ["blocking", "brotli", "deflate", "gzip", "rustls-tls", "json"] }
serde        = { workspace = true }
serde_json   = { workspace = true }